
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";

// Muat file .env secara manual sebelum konfigurasi Prisma dieksekusi
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
});
